### ISSUE TITLE
Running out of memory real bad

### ISSUE THREAD

**Issue by SharkWipf** [computer-whisperer/chiapos#8]
Watching your work on this fork with curious eyes, I've tried to build it to see how far you got.
After a bit of trial and error, I've managed to get it to compile on several different gcc versions, but any build I have got to compile immediately begins consuming copious amounts of memory, eventually running out of my entire 128GB RAM.

Steps to reproduce: 
- Change Dockerfile to build on Debian Sid instead of Ubuntu to get a newer gcc version
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
```
- run `docker-build.sh`, wait for it to be done
- run `docker-test.sh`. Code will immediately begin running out of memory.
```
$ ./docker-test.sh 
G: b011001111010111
G Slice: b01111
G Slice: b011001111
G Slice: b0
G Slice: b010111
G Slice: b
bytes: 103 174
Back to Bits: b0110011110101110
bytes: 128 0
Back to Bits: b1000000000000000
b01010000000
bytes: 80 0
H: b0101000000000000
I: b00101000000000000
G: b011001111010111
size: 15

Starting plotting progress into temporary dirs: . and .
ID: 23023404333717545b0a6f0c0dde9710e4d3fe2d5cc6cc0a090a0b818bab0f17
Plot size is: 18
Buffer size is: 11MiB
Using 16 buckets
Using 2 threads of stripe size 4000

Starting phase 1/4: Forward Propagation into tmp files... Sat May 22 13:37:30 2021
Allocating buckets
Killed
```

The same happens when building manually, outside of Docker.

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Dockerfile

no changes added to commit (use "git add" and/or "git commit -a")
```
```diff
diff --git a/Dockerfile b/Dockerfile
index 1d6e76b..68592e7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:20.04 as builder
+FROM debian:sid as builder
 
 ARG DEBIAN_FRONTEND=noninteractive
 
@@ -24,7 +24,7 @@ RUN cmake ../
 RUN cmake --build . -- -j `nproc`
 
 
-FROM ubuntu:20.04
+FROM debian:sid
 
 COPY --from=builder /app/build /app
```

**Comment by SharkWipf** [comment]
Running it on a different machine, it does seem to be working, and fast, but it's consuming over 256GiB of memory. Is this fork intended to be run in memory entirely?

**Comment by computer-whisperer** [comment]
This fork is designed to explore algorithms that are much more RAM heavy. Right now it uses upwards of 300GB, but in theory it should require less than 100GB. The motivation is that a lot of the CPU work in the stock plotter is driven from the requirement that everything be streamed through 4GB or so of RAM, and much more efficient approaches can be used if you allow for more.

**Comment by SharkWipf** [comment]
Ah yeah, that makes sense. I figured it was something like that, I just didn't expect the changes from upstream to be _that_ drastic, haha. 
I'd been attempting similar things configuration-wise, but it seems that without code changes it just isn't optimized enough to make a difference, and the lack of threading in the other phases makes it too inefficient to run single plots. Well, you've tackled all that, heh.
Unfortunately my 384GiB plotter is going away soon, but it's really interesting to follow the work you're doing nontheless, it seems very effective, impressive work!
